apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: default
  labels:
    app: haproxy
data:
  haproxy.cfg: |
    global
      daemon
      maxconn 256
    defaults
      mode http
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms
    frontend http-in
      bind *:80
      default_backend servers
    backend servers
      server server1 elasticsearch:9200 maxconn 32
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: config-volume
          configMap:
            name: haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: vip-service
spec:
  selector:
    app: haproxy
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
